In [1]:
import pandas as pd
import numpy as np

## 시도

In [2]:
# 혼잡시간강도 데이터
df=pd.read_csv('혼잡시간강도.csv')

In [11]:
df[:5]

sido_code  sigungu_code  emd_code week_type  TI_CG
0         37         37011   3701112   weekday  42.53
1         37         37030   3703038   weekday  52.40
2         21         21010   2101060   weekday  39.94
3         22         22050   2205062   weekday  48.96
4         37         37330   3733034   weekday  50.13

In [7]:
# 정의서 행정구역
doc=pd.read_excel('혼잡시간강도_행정구역_읍면동단위_데이터셋_명세서.xlsx',sheet_name='행정구역')

In [10]:
doc[:5]

시도코드   시도명칭  시군구코드 시군구명칭    읍면동코드 읍면동명칭
0    11  서울특별시  11010   종로구  1101053   사직동
1    11  서울특별시  11010   종로구  1101054   삼청동
2    11  서울특별시  11010   종로구  1101055   부암동
3    11  서울특별시  11010   종로구  1101056   평창동
4    11  서울특별시  11010   종로구  1101057   무악동

In [12]:
# 시도코드, 시도명칭만 가져오기
doc_si=doc[['시도코드','시도명칭']]
doc_si.head()

시도코드   시도명칭
0    11  서울특별시
1    11  서울특별시
2    11  서울특별시
3    11  서울특별시
4    11  서울특별시

In [25]:
doc_si['시도명칭'].unique()

array(['서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시',
       '세종특별자치시', '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도', '경상북도',
       '경상남도', '제주특별자치도'], dtype=object)

In [17]:
doc_si['시도코드'].unique()

array([11, 21, 22, 23, 24, 25, 26, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39],
      dtype=int64)

In [19]:
doc_si.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3504 entries, 0 to 3503
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   시도코드    3504 non-null   int64 
 1   시도명칭    3504 non-null   object
dtypes: int64(1), object(1)
memory usage: 54.9+ KB


In [26]:
# 찾아서 맞게 변형
df.loc[df["sido_code"] == 11, "시도"] = "서울특별시"
df.loc[df["sido_code"] == 21, "시도"] = "부산광역시"
df.loc[df["sido_code"] == 22, "시도"] = "대구광역시"
df.loc[df["sido_code"] == 23, "시도"] = "인천광역시"
df.loc[df["sido_code"] == 24, "시도"] = "광주광역시"
df.loc[df["sido_code"] == 25, "시도"] = "대전광역시"
df.loc[df["sido_code"] == 26, "시도"] = "울산광역시"
df.loc[df["sido_code"] == 29, "시도"] = "세종특별자치시"
df.loc[df["sido_code"] == 31, "시도"] = "경기도"
df.loc[df["sido_code"] == 32, "시도"] = "강원도"
df.loc[df["sido_code"] == 33, "시도"] = "충청북도"
df.loc[df["sido_code"] == 34, "시도"] = "충청남도"
df.loc[df["sido_code"] == 35, "시도"] = "전라북도"
df.loc[df["sido_code"] == 36, "시도"] = "전라남도"
df.loc[df["sido_code"] == 37, "시도"] = "경상북도"
df.loc[df["sido_code"] == 38, "시도"] = "경상남도"
df.loc[df["sido_code"] == 39, "시도"] = "제주특별자치도"

In [27]:
df

sido_code  sigungu_code  emd_code week_type  TI_CG     시도
0            37         37011   3701112   weekday  42.53   경상북도
1            37         37030   3703038   weekday  52.40   경상북도
2            21         21010   2101060   weekday  39.94  부산광역시
3            22         22050   2205062   weekday  48.96  대구광역시
4            37         37330   3733034   weekday  50.13   경상북도
...         ...           ...       ...       ...    ...    ...
3461         38         38080   3808052   weekday  84.80   경상남도
3462         22         22060   2206051   weekday  57.20  대구광역시
3463         24         24020   2402070   weekday  42.73  광주광역시
3464         31         31280   3128037   weekday  25.04    경기도
3465         31         31012   3101253   weekday  65.25    경기도

[3466 rows x 6 columns]

In [28]:
# 코드로 구현하는 다른 방법
df.loc[df["sido_code"] == doc_si['시도코드'].unique()[0] , "시도"] = doc_si['시도명칭'].unique()[0]

In [33]:
df.columns

Index(['sido_code', 'sigungu_code', 'emd_code', 'week_type', 'TI_CG', '시도'], dtype='object')

In [35]:
df=df.sort_values('sido_code')
df.head()

sido_code  sigungu_code  emd_code week_type  TI_CG     시도
745          11         11110   1111072   weekday  93.28  서울특별시
2128         11         11080   1108085   weekday  79.34  서울특별시
1279         11         11100   1110065   weekday  66.01  서울특별시
985          11         11100   1110053   weekday  79.33  서울특별시
2132         11         11230   1123075   weekday  78.40  서울특별시

## 구

In [65]:
df.head()

sido_code  sigungu_code  emd_code week_type  TI_CG     시도  시군구
745          11         11110   1111072   weekday  93.28  서울특별시  노원구
2128         11         11080   1108085   weekday  79.34  서울특별시  성북구
1279         11         11100   1110065   weekday  66.01  서울특별시  도봉구
985          11         11100   1110053   weekday  79.33  서울특별시  도봉구
2132         11         11230   1123075   weekday  78.40  서울특별시  강남구

In [66]:
doc_sigun=doc[['시도명칭','시군구코드','시군구명칭']]
doc_sigun.head()

시도명칭  시군구코드 시군구명칭
0  서울특별시  11010   종로구
1  서울특별시  11010   종로구
2  서울특별시  11010   종로구
3  서울특별시  11010   종로구
4  서울특별시  11010   종로구

In [75]:
doc_sigun=doc[(doc['시도명칭']=='서울특별시') | (doc['시도명칭']=='경기도')| (doc['시도명칭']=='인천광역시')]

In [76]:
doc_sigun

시도코드   시도명칭  시군구코드 시군구명칭    읍면동코드 읍면동명칭
0       11  서울특별시  11010   종로구  1101053   사직동
1       11  서울특별시  11010   종로구  1101054   삼청동
2       11  서울특별시  11010   종로구  1101055   부암동
3       11  서울특별시  11010   종로구  1101056   평창동
4       11  서울특별시  11010   종로구  1101057   무악동
...    ...    ...    ...   ...      ...   ...
1725    31    경기도  31380   양평군  3138037   청운면
1726    31    경기도  31380   양평군  3138038   양동면
1727    31    경기도  31380   양평군  3138039   지평면
1728    31    경기도  31380   양평군  3138040   용문면
1729    31    경기도  31380   양평군  3138041   개군면

[1138 rows x 6 columns]

In [77]:
doc_sigun=doc_sigun[['시도명칭','시군구코드','시군구명칭']]

In [78]:
doc_sigun['시군구코드'].unique()[0]

11010

In [79]:
doc_sigun['시군구코드'].nunique()

77

In [80]:
doc_sigun['시군구명칭'].nunique()

76

In [81]:
doc_sigun['시군구명칭'].unique()[0]

'종로구'

In [52]:
for i in range(doc_sigun['시군구코드'].nunique()):
    df.loc[df["sigungu_code"] == doc_sigun['시군구코드'].unique()[i] , "시군구"] = doc_sigun['시군구명칭'].unique()[i]

IndexError: index 227 is out of bounds for axis 0 with size 227

In [95]:
doc_sigun['시군구코드'].unique()

array([11010, 11020, 11030, 11040, 11050, 11060, 11070, 11080, 11090,
       11100, 11110, 11120, 11130, 11140, 11150, 11160, 11170, 11180,
       11190, 11200, 11210, 11220, 11230, 11240, 11250, 23010, 23020,
       23030, 23040, 23050, 23060, 23070, 23080, 23310, 23320, 31011,
       31012, 31013, 31014, 31021, 31022, 31023, 31030, 31041, 31042,
       31050, 31060, 31070, 31080, 31091, 31092, 31101, 31103, 31104,
       31110, 31120, 31130, 31140, 31150, 31160, 31170, 31180, 31191,
       31192, 31193, 31200, 31210, 31220, 31230, 31240, 31250, 31260,
       31270, 31280, 31350, 31370, 31380], dtype=int64)

In [85]:
doc_sigun['시군구명칭'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', '동구', '남구',
       '연수구', '남동구', '부평구', '계양구', '서구', '강화군', '옹진군', '수원시 장안구',
       '수원시 권선구', '수원시 팔달구', '수원시 영통구', '성남시 수정구', '성남시 중원구', '성남시 분당구',
       '의정부시', '안양시 만안구', '안양시 동안구', '부천시', '광명시', '평택시', '동두천시',
       '안산시 상록구', '안산시 단원구', '고양시 덕양구', '고양시 일산동구', '고양시 일산서구', '과천시',
       '구리시', '남양주시', '오산시', '시흥시', '군포시', '의왕시', '하남시', '용인시 처인구',
       '용인시 기흥구', '용인시 수지구', '파주시', '이천시', '안성시', '김포시', '화성시', '광주시',
       '양주시', '포천시', '여주시', '연천군', '가평군', '양평군'], dtype=object)

### 확인결과 서울, 인천 모두 중구가 있는 것을 확인할 수 있음

In [94]:
doc_sigun['시군구코드'].unique()[25]

23010

In [109]:
doc_sigun['시군구코드'].unique()

array([11010, 11020, 11030, 11040, 11050, 11060, 11070, 11080, 11090,
       11100, 11110, 11120, 11130, 11140, 11150, 11160, 11170, 11180,
       11190, 11200, 11210, 11220, 11230, 11240, 11250, 23010, 23020,
       23030, 23040, 23050, 23060, 23070, 23080, 23310, 23320, 31011,
       31012, 31013, 31014, 31021, 31022, 31023, 31030, 31041, 31042,
       31050, 31060, 31070, 31080, 31091, 31092, 31101, 31103, 31104,
       31110, 31120, 31130, 31140, 31150, 31160, 31170, 31180, 31191,
       31192, 31193, 31200, 31210, 31220, 31230, 31240, 31250, 31260,
       31270, 31280, 31350, 31370, 31380], dtype=int64)

In [125]:
a=[]
for i in range(doc_sigun['시군구코드'].nunique()):
    a.append(doc_sigun['시군구코드'].unique()[i])
print(a)

[11010, 11020, 11030, 11040, 11050, 11060, 11070, 11080, 11090, 11100, 11110, 11120, 11130, 11140, 11150, 11160, 11170, 11180, 11190, 11200, 11210, 11220, 11230, 11240, 11250, 23010, 23020, 23030, 23040, 23050, 23060, 23070, 23080, 23310, 23320, 31011, 31012, 31013, 31014, 31021, 31022, 31023, 31030, 31041, 31042, 31050, 31060, 31070, 31080, 31091, 31092, 31101, 31103, 31104, 31110, 31120, 31130, 31140, 31150, 31160, 31170, 31180, 31191, 31192, 31193, 31200, 31210, 31220, 31230, 31240, 31250, 31260, 31270, 31280, 31350, 31370, 31380]


In [126]:
b=[]
for i in range(25):
    b.append(doc_sigun['시군구명칭'].unique()[i])
print(b)

['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구']


In [127]:
# for i in range(26,77):
#     a.append(doc_sigun['시군구코드'].unique()[i])
# print(a)

In [128]:
b.append('인천_중구')

In [129]:
b

['종로구',
 '중구',
 '용산구',
 '성동구',
 '광진구',
 '동대문구',
 '중랑구',
 '성북구',
 '강북구',
 '도봉구',
 '노원구',
 '은평구',
 '서대문구',
 '마포구',
 '양천구',
 '강서구',
 '구로구',
 '금천구',
 '영등포구',
 '동작구',
 '관악구',
 '서초구',
 '강남구',
 '송파구',
 '강동구',
 '인천_중구']

In [130]:

for i in range(25,76):
    b.append(doc_sigun['시군구명칭'].unique()[i])
print(b)

['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', '인천_중구', '동구', '남구', '연수구', '남동구', '부평구', '계양구', '서구', '강화군', '옹진군', '수원시 장안구', '수원시 권선구', '수원시 팔달구', '수원시 영통구', '성남시 수정구', '성남시 중원구', '성남시 분당구', '의정부시', '안양시 만안구', '안양시 동안구', '부천시', '광명시', '평택시', '동두천시', '안산시 상록구', '안산시 단원구', '고양시 덕양구', '고양시 일산동구', '고양시 일산서구', '과천시', '구리시', '남양주시', '오산시', '시흥시', '군포시', '의왕시', '하남시', '용인시 처인구', '용인시 기흥구', '용인시 수지구', '파주시', '이천시', '안성시', '김포시', '화성시', '광주시', '양주시', '포천시', '여주시', '연천군', '가평군', '양평군']


In [131]:
len(b)

77

In [133]:
len(a)

77

In [134]:
sigun=pd.DataFrame({'시군구코드':a,'시군구명칭':b})
sigun

시군구코드 시군구명칭
0   11010   종로구
1   11020    중구
2   11030   용산구
3   11040   성동구
4   11050   광진구
..    ...   ...
72  31270   포천시
73  31280   여주시
74  31350   연천군
75  31370   가평군
76  31380   양평군

[77 rows x 2 columns]

In [135]:
for i in range(sigun['시군구코드'].nunique()):
    df.loc[df["sigungu_code"] == sigun['시군구코드'].unique()[i] , "시군구"] = sigun['시군구명칭'].unique()[i]

In [137]:
df=df[(df['시도']=='서울특별시') | (df['시도']=='경기도')| (df['시도']=='인천광역시')]

In [138]:
df

sido_code  sigungu_code  emd_code week_type  TI_CG     시도      시군구
745          11         11110   1111072   weekday  93.28  서울특별시      노원구
2128         11         11080   1108085   weekday  79.34  서울특별시      성북구
1279         11         11100   1110065   weekday  66.01  서울특별시      도봉구
985          11         11100   1110053   weekday  79.33  서울특별시      도봉구
2132         11         11230   1123075   weekday  78.40  서울특별시      강남구
...         ...           ...       ...       ...    ...    ...      ...
3206         31         31021   3102160   weekday  47.71    경기도  성남시 수정구
3208         31         31280   3128033   weekday  29.34    경기도      여주시
3220         31         31260   3126053   weekday  51.49    경기도      양주시
3231         31         31110   3111053   weekday  59.63    경기도      과천시
3199         31         31130   3113054   weekday  52.02    경기도     남양주시

[1129 rows x 7 columns]

In [140]:
df.to_csv('수도권 혼잡시간강도.csv',encoding='utf-8-sig', index=False)